#!/bin/bash

WK_DIR=$(dirname $(readlink -f $0))
cd ${WK_DIR}/../
rm -rf addons aclocal.m4 autom4te.cache compile config* depcomp install-sh \
   ltmain.sh Makefile.* missing
${WK_DIR}/../debian/rules pre-clean

